project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-On Exercises"
        menu:
          - text: "Exercise 1: Basics"
            href: "hands_on_ex/hands_on_ex_01/hands_on_ex_01.html"
          - text: "Exercise 2: Annotations, Themes, Multiple Graphs"
            href: "hands_on_ex/hands_on_ex_02/hands_on_ex_02.html"
          - text: "Exercise 3: Interactivity and Animations"
            href: "hands_on_ex/hands_on_ex_03/hands_on_ex_03.html"
          - text: "Exercise 4: Visualising Statistics & Uncertainty"
            href: "hands_on_ex/hands_on_ex_04/hands_on_ex_04.html"
          - text: "Exercise 6: Multivariate Analysis"
            href: "hands_on_ex/hands_on_ex_06/hands_on_ex_06.html"
      - text: "In-Class Exercises"
        menu:
          - text: "Exercise 1: Programming Elegant DataVis with ggplot2"
            href: "in_class_ex/in_class_ex_01/in_class_ex_01.html"
          - text: "Exercise 3"
            href: "in_class_ex/in_class_ex_03/in_class_ex_03.html"
          - text: "Exercise 4: Visualising Normal Distribution"
            href: "in_class_ex/in_class_ex_04/in_class_ex_04.html"
          - text: "Exercise 5: Visualising Graph Data"
            href: "in_class_ex/in_class_ex_05/in_class_ex_05.html"
      - text: "Take-Home Exercises"
        menu:
          - text: "Exercise 1: City of Engagement"
            href: "take_home_ex/take_home_ex_01/take_home_ex_01.html"
          - text: "Exercise 2: VAST Challenge 2023, Mini-Challenge 2"
            href: "take_home_ex/take_home_ex_02/take_home_ex_02.html"
          - text: "Exercise 3: VAST Challenge 2023, Mini-Challenge 3"
            href: "take_home_ex/take_home_ex_03/take_home_ex_03.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: true
  

